version: '3.8'

services:
  app:
    build: .
    image: flask-task-app:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://admin:1234@mysql:3306/flask_task_db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flask_task_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3307:3306"  # Host port 3307 maps to container port 3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data: